jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle
    - continue-on-error: true
      name: Build and run Tests
      run: "if [[ \"$GITHUB_EVENT_NAME\" == 'schedule' ]]; then\n  echo running with\
        \ real downloader\n  ./gradlew check --stacktrace -Ddownloader=REAL\nelse\n\
        \  echo running with mock downloader\n  ./gradlew check --stacktrace -Ddownloader=MOCK\n\
        fi\n"
    - continue-on-error: true
      if: failure()
      name: Upload test reports when failure occurs
      uses: actions/upload-artifact@v4
      with:
        name: NewPipeExtractor-test-reports
        path: extractor/build/reports/tests/test/**
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
permissions:
  contents: read
